-- 04 — Storage integrations
--
-- Run as ACCOUNTADMIN, after 03. Creating a storage integration requires
-- ACCOUNTADMIN; it cannot be delegated to the transformer roles.
--
-- ORDER MATTERS. This is the bidirectional trust setup:
--
--   1. Run PART A below. It creates the integrations referencing IAM role
--      ARNs that DO NOT EXIST YET. That is fine — Snowflake does not
--      validate the ARN at creation time.
--   2. Run PART B (the DESC statements). Copy STORAGE_AWS_IAM_USER_ARN and
--      STORAGE_AWS_EXTERNAL_ID for each.
--   3. Put those four values into infra/terraform/snowflake_integration.tf
--      as variables, and apply. That creates the roles with a trust policy
--      naming Snowflake's IAM user and external ID.
--   4. Run PART C to verify the trust actually works end to end.
--
-- Step 4 is not optional. Steps 1-3 can all appear to succeed while the
-- trust is broken, and the failure only shows up later as an opaque
-- permissions error on a COPY.

USE ROLE ACCOUNTADMIN;

-- ==========================================================================
-- PART A — create the integrations
-- ==========================================================================
--
-- STORAGE_ALLOWED_LOCATIONS is the Snowflake-side boundary. Even if the IAM
-- policy were too broad, Snowflake will not read outside these prefixes.
-- Two independent controls on the same access, which is the point.
--
-- Note the trailing slashes. Without them the prefix match is looser than
-- intended.

CREATE STORAGE INTEGRATION IF NOT EXISTS RETAIL_DEV_S3_INTEGRATION
  TYPE                      = EXTERNAL_STAGE
  STORAGE_PROVIDER          = 'S3'
  ENABLED                   = TRUE
  STORAGE_AWS_ROLE_ARN      = 'arn:aws:iam::009073574996:role/retail-dev-snowflake-integration-role'
  STORAGE_ALLOWED_LOCATIONS = (
    's3://sd-retail-dev-staged-009073574996-eu-west-2-an/orders/',
    's3://sd-retail-dev-staged-009073574996-eu-west-2-an/_audit/'
  )
  COMMENT = 'Read staged Parquet and recon audit records - dev';

CREATE STORAGE INTEGRATION IF NOT EXISTS RETAIL_PROD_S3_INTEGRATION
  TYPE                      = EXTERNAL_STAGE
  STORAGE_PROVIDER          = 'S3'
  ENABLED                   = TRUE
  STORAGE_AWS_ROLE_ARN      = 'arn:aws:iam::009073574996:role/retail-prod-snowflake-integration-role'
  STORAGE_ALLOWED_LOCATIONS = (
    's3://sd-retail-prod-staged-009073574996-eu-west-2-an/orders/',
    's3://sd-retail-prod-staged-009073574996-eu-west-2-an/_audit/'
  )
  COMMENT = 'Read staged Parquet and recon audit records - prod';

-- Transformer roles need USAGE to create stages on the integration.
-- Without this only ACCOUNTADMIN can use it, and dbt would fail.
GRANT USAGE ON INTEGRATION RETAIL_DEV_S3_INTEGRATION  TO ROLE RETAIL_TRANSFORMER_DEV;
GRANT USAGE ON INTEGRATION RETAIL_PROD_S3_INTEGRATION TO ROLE RETAIL_TRANSFORMER_PROD;

-- ==========================================================================
-- PART B — read the generated trust values
-- ==========================================================================
--
-- Take STORAGE_AWS_IAM_USER_ARN and STORAGE_AWS_EXTERNAL_ID from each of
-- these and put them into Terraform. They are generated by Snowflake and
-- cannot be predicted.
--
-- STORAGE_AWS_IAM_USER_ARN is usually the same for both integrations — it is
-- per Snowflake account, not per integration. STORAGE_AWS_EXTERNAL_ID is
-- unique per integration, and that uniqueness is what stops one integration
-- being used to assume the other's role.

DESC INTEGRATION RETAIL_DEV_S3_INTEGRATION;
DESC INTEGRATION RETAIL_PROD_S3_INTEGRATION;

-- ==========================================================================
-- PART C — verify, AFTER the Terraform apply
-- ==========================================================================
--
-- Create a stage and list it. If the trust policy is wrong this fails here
-- rather than silently later.
--
-- IAM changes can take a minute or two to propagate. A failure immediately
-- after apply is worth retrying once before investigating.

CREATE STAGE IF NOT EXISTS RETAIL_DEV.RAW.STG_ORDERS
  STORAGE_INTEGRATION = RETAIL_DEV_S3_INTEGRATION
  URL                 = 's3://sd-retail-dev-staged-009073574996-eu-west-2-an/orders/'
  FILE_FORMAT         = (TYPE = PARQUET)
  COMMENT             = 'Staged Parquet, partitioned year=/month=';

CREATE STAGE IF NOT EXISTS RETAIL_DEV.OPS.STG_RECON
  STORAGE_INTEGRATION = RETAIL_DEV_S3_INTEGRATION
  URL                 = 's3://sd-retail-dev-staged-009073574996-eu-west-2-an/_audit/recon/'
  FILE_FORMAT         = (TYPE = JSON)
  COMMENT             = 'Reconciliation audit records from the Glue job';

-- This is the actual test. It should list the Parquet files written by the
-- Glue job for the months loaded so far.
LIST @RETAIL_DEV.RAW.STG_ORDERS;
LIST @RETAIL_DEV.OPS.STG_RECON;

-- And prove the boundary holds. This path is outside
-- STORAGE_ALLOWED_LOCATIONS and must fail even though the IAM role could
-- technically reach the bucket.
--
--   CREATE STAGE RETAIL_DEV.RAW.STG_SHOULD_FAIL
--     STORAGE_INTEGRATION = RETAIL_DEV_S3_INTEGRATION
--     URL = 's3://sd-retail-dev-staged-009073574996-eu-west-2-an/_glue-temp/';
--
-- If that succeeds, STORAGE_ALLOWED_LOCATIONS is not doing what it should.

-- Prod stages — same shape. Create when prod data exists.
--
-- CREATE STAGE IF NOT EXISTS RETAIL_PROD.RAW.STG_ORDERS
--   STORAGE_INTEGRATION = RETAIL_PROD_S3_INTEGRATION
--   URL                 = 's3://sd-retail-prod-staged-009073574996-eu-west-2-an/orders/'
--   FILE_FORMAT         = (TYPE = PARQUET);
