# Values generated by Snowflake when the storage integrations are created.
# Read them with:
#
#   DESC INTEGRATION RETAIL_DEV_S3_INTEGRATION;
#   DESC INTEGRATION RETAIL_PROD_S3_INTEGRATION;
#
# Not secrets — they are identifiers, not credentials. But they are
# account-specific, so they live in terraform.tfvars (gitignored) with an
# example file committed showing the shape.

variable "snowflake_iam_user_arn" {
  description = "STORAGE_AWS_IAM_USER_ARN — the AWS identity Snowflake assumes from. Same for all integrations in an account."
  type        = string
}

variable "snowflake_external_id_dev" {
  description = "STORAGE_AWS_EXTERNAL_ID for the dev integration. Unique per integration."
  type        = string
}

variable "snowflake_external_id_prod" {
  description = "STORAGE_AWS_EXTERNAL_ID for the prod integration."
  type        = string
}
