USE ROLE ACCOUNTADMIN;

-- XS is the smallest. Auto-suspend at 60s matters more than size for cost:
-- an idle warehouse bills by the second until it suspends.
CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS RETAIL_DEV;
CREATE DATABASE IF NOT EXISTS RETAIL_PROD;

-- Mirrors the S3 layer structure. RAW holds what lands from S3; dbt builds
-- STAGING, INTERMEDIATE and MARTS. OPS holds the reconciliation audit
-- records so pipeline metrics are queryable alongside the data.
CREATE SCHEMA IF NOT EXISTS RETAIL_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS RETAIL_DEV.STAGING;
CREATE SCHEMA IF NOT EXISTS RETAIL_DEV.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS RETAIL_DEV.MARTS;
CREATE SCHEMA IF NOT EXISTS RETAIL_DEV.OPS;

CREATE SCHEMA IF NOT EXISTS RETAIL_PROD.RAW;
CREATE SCHEMA IF NOT EXISTS RETAIL_PROD.STAGING;
CREATE SCHEMA IF NOT EXISTS RETAIL_PROD.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS RETAIL_PROD.MARTS;
CREATE SCHEMA IF NOT EXISTS RETAIL_PROD.OPS;

-- Role for dbt, separate from ACCOUNTADMIN. Same segregation principle as
-- the AWS pipeline execution roles.
CREATE ROLE IF NOT EXISTS RETAIL_TRANSFORMER;
GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE RETAIL_TRANSFORMER;
GRANT ALL ON DATABASE RETAIL_DEV TO ROLE RETAIL_TRANSFORMER;
GRANT ALL ON ALL SCHEMAS IN DATABASE RETAIL_DEV TO ROLE RETAIL_TRANSFORMER;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE RETAIL_DEV TO ROLE RETAIL_TRANSFORMER;
GRANT ROLE RETAIL_TRANSFORMER TO USER soumyadeep007;